* Kick people who abuse the bot
Implement some tracking of how often people trigger bot functions and if they clear a limit they get kicked (preferably with an entertaining message. 

Will need to get the bot to identify to services, give it ops and implement to logic to actually kick folks.

Could probably do with a whitelist of people who are allowed to abuse the bot without getting kicked.

Need to speak to Shell to get the password for identifying as hackerdeenbot. 
* Logging
Log messages to the channel to a database so that we can then do some stats type things on them.
* Logging URLs
Want to expose a history of URLs that were mentioned in channel - could be done as something on top of the logging mentioned above. 

** Display title of URLs
similar to what many other IRC bots do: display the title of the page when a URL is mentioned in channel. A last mentioned by $person feature would also be useful (and would build on top of the logging of URLs mentioned above). 

There was another bot doing this but it was deemed to be too annoying and got banned. 
* Expose stats about the channel
 - # of people there
 - measure of activity
* Announce door opening
Related to doorbot logging to something on the internet. Once that is there could then do with the unlock events being announced to the channel. 

There are now events exposed from the spaceAPI for this so could easily hook it up in the check status function. Catch people going in and not opening the space. 
* Relay tweets to IRC
Could relay when someone tweets with or at the space twitter. Possibly follow hash tags as well.
* Rejig how functions work
Have the main loop just call them all and let them decide for themselves if they want to do anything. 
* Rejig help function
Use doc strings from the functions to get help text for the enabled functions rather than needing to update one global space thing. 
* define events somewhere other than the source
The events for time should be somewhere other than in the source.
* Have the bot say something if the channel is quiet for too long
** Ask someone to tell a joke
** give a cah result
** something from my fortune file
Make a DB for this and let the bot add to it. 
** Quote from history
Once it is keeping logs could pick a "noteworthy" entry to quote. Need to decide how "noteworthy" is determined...
** Entry from 57N QDB
* Answer yes or no questions/ make choices
Yes/no is easy. Making choices means doing some processing to identify the choices from the question. 
